# Generated by Django 3.0.8 on 2021-06-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tag', models.ManyToManyField(to='portfolio_project.Tag')),
            ],
        ),
    ]
