# Generated by Django 3.0.8 on 2021-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='tag',
            field=models.ManyToManyField(blank=True, to='portfolio_project.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
