# Generated by Django 3.0.8 on 2021-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0004_auto_20210625_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=100, null=' '),
            preserve_default=' ',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
