# Generated by Django 3.0.8 on 2021-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0005_auto_20210625_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=100, null=' ', unique=True),
        ),
    ]
