# Generated by Django 3.0.8 on 2021-07-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0006_auto_20210721_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='thumbnail',
            field=models.ImageField(null=' ', upload_to=''),
            preserve_default=' ',
        ),
    ]
