# Generated by Django 3.0.8 on 2021-07-23 14:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0007_portfolio_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
