# Generated by Django 3.0.8 on 2021-07-26 16:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0008_auto_20210723_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
